
export const landingProductItems = [
  {
    id: 1,
    name: "GardenGuard Insect Killer",
    image_url: "./src/assets/pic3.jpg",
    price: 12.99,
    description: "Effective insect killer for protecting your garden plants.",
  },
  {
    id: 2,
    name: "BugBuster Organic Spray",
    image_url: "./src/assets/pic4.jpg",
    price: 15.49,
    description: "Organic insect spray to keep bugs away from your crops.",
  },
  {
    id: 3,
    name: "MosquitoShield Repellent",
    image_url: "./src/assets/pic5.jpg",
    price: 8.99,
    description: "Powerful mosquito repellent for indoor and outdoor use.",
  },
  {
    id: 4,
    name: "CropDefender Granules",
    image_url: "./src/assets/pic3.jpg",
    price: 18.79,
    description: "Granule form insecticide for protecting crops in large areas.",
  },
];



export const productItems = [
        {
            id: 1,
            name: "GardenGuard Insect Killer",
            image_url: "./src/assets/pic3.jpg",
            price: 12.99,
            description: "Effective insect killer for protecting your garden plants.",
          },
          {
            id: 2,
            name: "BugBuster Organic Spray",
            image_url: "./src/assets/pic4.jpg",
            price: 15.49,
            description: "Organic insect spray to keep bugs away from your crops.",
          },
          {
            id: 3,
            name: "MosquitoShield Repellent",
            image_url: "./src/assets/pic5.jpg",
            price: 8.99,
            description: "Powerful mosquito repellent for indoor and outdoor use.",
          },
          {
            id: 4,
            name: "CropDefender Granules",
            image_url: "./src/assets/pic3.jpg",
            price: 18.79,
            description: "Granule form insecticide for protecting crops in large areas.",
          },
          {
            id: 5,
            name: "AntStop Ant Bait",
            image_url: "./src/assets/pic4.jpg",
            price: 6.99,
            description: "Effective ant bait for controlling ant infestations.",
          },
          {
            id: 6,
            name: "FlyAway Fly Repellent",
            image_url: "./src/assets/pic5.jpg",
            price: 9.99,
            description: "Repellent spray to keep flies away from your space.",
          },
          
        {
            id: 7,
            name: "GardenGuard Insect Killer",
            image_url: "./src/assets/pic3.jpg",
            price: 12.99,
            description: "Effective insect killer for protecting your garden plants.",
          },
          {
            id: 8,
            name: "BugBuster Organic Spray",
            image_url: "./src/assets/pic4.jpg",
            price: 15.49,
            description: "Organic insect spray to keep bugs away from your crops.",
          },
          {
            id: 9,
            name: "MosquitoShield Repellent",
            image_url: "./src/assets/pic5.jpg",
            price: 8.99,
            description: "Powerful mosquito repellent for indoor and outdoor use.",
          },
          {
            id: 10,
            name: "CropDefender Granules",
            image_url: "./src/assets/pic3.jpg",
            price: 18.79,
            description: "Granule form insecticide for protecting crops in large areas.",
          },
          {
            id: 11,
            name: "AntStop Ant Bait",
            image_url: "./src/assets/pic4.jpg",
            price: 6.99,
            description: "Effective ant bait for controlling ant infestations.",
          },
          {
            id: 12,
            name: "FlyAway Fly Repellent",
            image_url: "./src/assets/pic5.jpg",
            price: 9.99,
            description: "Repellent spray to keep flies away from your space.",
          },
          {
            id: 13,
            name: "GardenGuard Insect Killer",
            image_url: "./src/assets/pic3.jpg",
            price: 12.99,
            description: "Effective insect killer for protecting your garden plants.",
          },
          {
            id: 14,
            name: "BugBuster Organic Spray",
            image_url: "./src/assets/pic4.jpg",
            price: 15.49,
            description: "Organic insect spray to keep bugs away from your crops.",
          },
          {
            id: 15,
            name: "MosquitoShield Repellent",
            image_url: "./src/assets/pic5.jpg",
            price: 8.99,
            description: "Powerful mosquito repellent for indoor and outdoor use.",
          },
          {
            id: 16,
            name: "CropDefender Granules",
            image_url: "./src/assets/pic3.jpg",
            price: 18.79,
            description: "Granule form insecticide for protecting crops in large areas.",
          },
          {
            id: 17,
            name: "AntStop Ant Bait",
            image_url: "./src/assets/pic4.jpg",
            price: 6.99,
            description: "Effective ant bait for controlling ant infestations.",
          },
          {
            id: 18,
            name: "GardenGuard Insect Killer",
            image_url: "./src/assets/pic5.jpg",
            price: 12.99,
            description: "Effective insect killer for protecting your garden plants.",
          },
          {
            id: 19,
            name: "BugBuster Organic Spray",
            image_url: "./src/assets/pic3.jpg",
            price: 15.49,
            description: "Organic insect spray to keep bugs away from your crops.",
          },
          {
            id: 20,
            name: "MosquitoShield Repellent",
            image_url: "./src/assets/pic4.jpg",
            price: 8.99,
            description: "Powerful mosquito repellent for indoor and outdoor use.",
          },
];